CREATE TABLE IF NOT EXISTS chat(id SERIAL PRIMARY KEY, name TEXT, msg TEXT, ts TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS topics(id SERIAL PRIMARY KEY, name TEXT, creator TEXT, description TEXT, ts TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS topic_msgs(id SERIAL PRIMARY KEY, topic_id INTEGER, name TEXT, msg TEXT, ts TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS threads(id SERIAL PRIMARY KEY, title TEXT, author TEXT, body TEXT, ts TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS replies(id SERIAL PRIMARY KEY, thread_id INTEGER, author TEXT, body TEXT, ts TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY, username TEXT UNIQUE, salt TEXT, hash TEXT, role TEXT DEFAULT 'user', banned BOOLEAN DEFAULT FALSE, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS tokens(token TEXT PRIMARY KEY, user_id INTEGER, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS ip_logs(id SERIAL PRIMARY KEY, user_id INTEGER, ip TEXT, ts TIMESTAMP DEFAULT NOW());
